//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastMoney.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public int id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string type { get; set; }
        public string icon { get; set; }
        public Nullable<int> sender { get; set; }
        public Nullable<int> recipient { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
